2022-01-31 11:45:13,976 INFO    Thread-2  :16635 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,977 WARNING Thread-2  :16635 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,977 INFO    Thread-2  :16635 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,977 INFO    Thread-2  :16635 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,977 INFO    Thread-2  :16635 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,977 INFO    Thread-2  :16635 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,977 INFO    Thread-2  :16635 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,977 INFO    Thread-2  :16635 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,978 INFO    Thread-2  :16635 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,978 INFO    Thread-2  :16632 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,978 WARNING Thread-2  :16632 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,978 INFO    Thread-2  :16632 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,978 INFO    Thread-2  :16632 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,978 INFO    Thread-2  :16632 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,978 INFO    Thread-2  :16632 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,978 INFO    Thread-2  :16623 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,978 INFO    Thread-2  :16632 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,979 WARNING Thread-2  :16623 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,979 INFO    Thread-2  :16632 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,979 INFO    Thread-2  :16632 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,979 INFO    Thread-2  :16637 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,979 WARNING Thread-2  :16637 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,979 INFO    Thread-2  :16637 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,979 INFO    Thread-2  :16623 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,979 INFO    Thread-2  :16637 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,980 INFO    Thread-2  :16637 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,980 INFO    Thread-2  :16637 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,980 INFO    Thread-2  :16637 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,980 INFO    Thread-2  :16637 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,980 INFO    Thread-2  :16637 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,982 WARNING Thread-2  :16631 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,982 INFO    Thread-2  :16634 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,982 WARNING Thread-2  :16634 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,982 INFO    Thread-2  :16634 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,982 INFO    Thread-2  :16634 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,982 INFO    Thread-2  :16634 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,982 INFO    Thread-2  :16631 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,983 INFO    Thread-2  :16634 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,983 INFO    Thread-2  :16634 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,983 INFO    Thread-2  :16634 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,983 INFO    Thread-2  :16625 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,983 WARNING Thread-2  :16625 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,983 INFO    Thread-2  :16634 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,983 INFO    Thread-2  :16625 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,983 INFO    Thread-2  :16625 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,983 INFO    Thread-2  :16625 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,983 INFO    Thread-2  :16625 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,983 INFO    Thread-2  :16625 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,984 INFO    Thread-2  :16625 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,984 INFO    Thread-2  :16625 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,984 INFO    Thread-2  :16633 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,984 WARNING Thread-2  :16633 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,985 INFO    Thread-2  :16633 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_setup.py:_flush():71] setting env: {'root_dir': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10', 'entity': 'paulina', 'project': 'ImageClassifierCIFAR10', 'run_id': 'tqws4024', 'sweep_id': 'mjc1k0xo', 'sweep_param_path': '/blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/sweep-mjc1k0xo/config-tqws4024.yaml'}
2022-01-31 11:45:13,986 WARNING Thread-2  :16636 [wandb_setup.py:_flush():71] could not save program above cwd: /home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/ray/workers/default_worker.py
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_init.py:_log_setup():371] Logging user logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug.log
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_init.py:_log_setup():372] Logging internal logs to /blue/fsaeed/paulinaacostacev/ImageClassifierCIFAR10/wandb/run-20220131_114513-tqws4024/logs/debug-internal.log
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_init.py:init():404] calling init triggers
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_init.py:init():409] wandb.init called with sweep_config: {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
config: {}
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [wandb_init.py:init():460] starting backend
2022-01-31 11:45:13,986 INFO    Thread-2  :16636 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-31 11:45:13,993 INFO    Thread-2  :16635 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:13,994 INFO    Thread-2  :16623 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:13,995 INFO    Thread-2  :16632 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:13,996 INFO    Thread-2  :16637 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:13,997 INFO    Thread-2  :16634 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:13,997 INFO    Thread-2  :16631 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:14,000 INFO    Thread-2  :16625 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:14,001 INFO    Thread-2  :16636 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:14,001 INFO    Thread-2  :16633 [backend.py:ensure_launched():216] starting backend process...
2022-01-31 11:45:14,003 INFO    Thread-2  :16623 [backend.py:ensure_launched():221] started backend process with pid: 18140
2022-01-31 11:45:14,004 INFO    Thread-2  :16635 [backend.py:ensure_launched():221] started backend process with pid: 18147
2022-01-31 11:45:14,004 INFO    Thread-2  :16623 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,005 INFO    Thread-2  :16634 [backend.py:ensure_launched():221] started backend process with pid: 18155
2022-01-31 11:45:14,005 INFO    Thread-2  :16635 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,006 INFO    Thread-2  :16631 [backend.py:ensure_launched():221] started backend process with pid: 18166
2022-01-31 11:45:14,006 INFO    Thread-2  :16634 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,006 INFO    Thread-2  :16632 [backend.py:ensure_launched():221] started backend process with pid: 18165
2022-01-31 11:45:14,007 INFO    Thread-2  :16637 [backend.py:ensure_launched():221] started backend process with pid: 18174
2022-01-31 11:45:14,007 INFO    Thread-2  :16623 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,007 INFO    Thread-2  :16635 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,007 INFO    Thread-2  :16631 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,008 INFO    Thread-2  :16634 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,008 INFO    Thread-2  :16632 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,009 INFO    Thread-2  :16637 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,009 INFO    Thread-2  :16631 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,009 INFO    Thread-2  :16623 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,009 INFO    Thread-2  :16635 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,009 INFO    Thread-2  :16636 [backend.py:ensure_launched():221] started backend process with pid: 18190
2022-01-31 11:45:14,009 INFO    Thread-2  :16625 [backend.py:ensure_launched():221] started backend process with pid: 18192
2022-01-31 11:45:14,010 INFO    Thread-2  :16632 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,010 INFO    Thread-2  :16634 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,010 INFO    Thread-2  :16637 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,011 INFO    Thread-2  :16636 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,011 INFO    Thread-2  :16633 [backend.py:ensure_launched():221] started backend process with pid: 18204
2022-01-31 11:45:14,011 INFO    Thread-2  :16625 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,011 INFO    Thread-2  :16635 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,011 INFO    Thread-2  :16631 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,012 INFO    Thread-2  :16632 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,012 INFO    Thread-2  :16633 [wandb_init.py:init():469] backend started and connected
2022-01-31 11:45:14,012 INFO    Thread-2  :16637 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,013 INFO    Thread-2  :16634 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,013 INFO    Thread-2  :16631 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,013 INFO    Thread-2  :16625 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,013 INFO    Thread-2  :16636 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,013 INFO    Thread-2  :16632 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,014 INFO    Thread-2  :16637 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,014 INFO    Thread-2  :16633 [wandb_run.py:_config_callback():956] config_cb None None {'learning_rate': 0.0007285039609268398, 'optimizer': 'adam'}
2022-01-31 11:45:14,015 INFO    Thread-2  :16625 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,017 INFO    Thread-2  :16625 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,017 INFO    Thread-2  :16623 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,018 INFO    Thread-2  :16636 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,019 INFO    Thread-2  :16633 [wandb_init.py:init():533] updated telemetry
2022-01-31 11:45:14,019 INFO    Thread-2  :16636 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:14,021 INFO    Thread-2  :16633 [wandb_init.py:init():563] communicating current version
2022-01-31 11:45:15,510 INFO    Thread-2  :16637 [wandb_init.py:init():568] got version response 
2022-01-31 11:45:15,510 INFO    Thread-2  :16637 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:15,651 INFO    Thread-2  :16637 [wandb_init.py:init():606] starting run threads in backend
2022-01-31 11:45:17,584 INFO    Thread-2  :16637 [wandb_run.py:_console_start():1810] atexit reg
2022-01-31 11:45:17,585 INFO    Thread-2  :16637 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-31 11:45:17,585 INFO    Thread-2  :16637 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-31 11:45:17,586 ERROR   Thread-2  :16637 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-01-31 11:45:17,588 INFO    Thread-2  :16637 [wandb_init.py:init():633] run started, returning control to user process
2022-01-31 11:45:19,012 INFO    Thread-2  :16635 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,013 INFO    Thread-2  :16634 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,013 INFO    Thread-2  :16631 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,014 INFO    Thread-2  :16632 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,017 INFO    Thread-2  :16625 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,018 INFO    Thread-2  :16623 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,020 INFO    Thread-2  :16636 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,021 ERROR   Thread-2  :16635 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,021 INFO    Thread-2  :16633 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-31 11:45:19,022 ERROR   Thread-2  :16631 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,022 ERROR   Thread-2  :16634 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,024 ERROR   Thread-2  :16632 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,027 ERROR   Thread-2  :16625 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,027 ERROR   Thread-2  :16623 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,029 ERROR   Thread-2  :16636 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-31 11:45:19,031 ERROR   Thread-2  :16633 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/paulinaacostacev/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
